# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 049913f68f783d853a4e7833be5676fd2c2f008264cdb3c2641379d8a92ee638716c7b73838450b3f3f933a93c496ca8eaff84d4eafd0a7fa947bbf901e50343

test:
  secret_key_base: 8bd501c15edd3108df30b50c9fb58d3eb955049d2a9d4b658d69b1159beb9bfd282041659e7263c8f046882e9c28d480113f55fa106c84373efb3d5fb3de217c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
